/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Acceso_Base_de_Datos.VisitaData;
import Entidades.Visita;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elmsn
 */
public class TratamientoPorTipo extends javax.swing.JInternalFrame {
private DefaultTableModel modelo= new DefaultTableModel();
    /**
     * Creates new form TratamientoPorTipo
     */
    public TratamientoPorTipo() {
        initComponents();
        armarTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtTratamiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaTratamientos = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRATAMIENTO POR TIPO");

        jLabel2.setText("TRATAMIENTO A BUSCAR:");

        jtTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTratamientoActionPerformed(evt);
            }
        });
        jtTratamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTratamientoKeyReleased(evt);
            }
        });

        jTablaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaTratamientos);

        jbSalir.setText("SALIR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTratamientoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jtTratamientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTratamientoKeyReleased
     //CODIGO A REVISAR O BUSCAR OTRA FORMA DE MEJORARLO
        borrarFilas();
        VisitaData visitData = new VisitaData();

        List<Visita> visitas = visitData.listarVisitas();
        for (Visita visit : visitas) {
            if (visit.getTratamiento().getTipoTratamiento().toLowerCase().startsWith(jtTratamiento.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    visit.getFechaVisita(),
                    visit.getTratamiento().getTipoTratamiento(),
                    visit.getMascota().getNombreAlias(),
                    visit.getTratamiento().getDescripcion(),
                    visit.getTratamiento().getImporte(),
                    visit.getTratamiento().isEstadoTratamiento()
                });
            }

        }
    }//GEN-LAST:event_jtTratamientoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaTratamientos;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtTratamiento;
    // End of variables declaration//GEN-END:variables
private void armarTabla(){
    modelo.addColumn("Fecha ");// fecha de visita
    modelo.addColumn("Tratamiento ");// tipodeTratamiento de tratamiento
    modelo.addColumn("Mascota ");
    modelo.addColumn("Descripcion ");// descripcion del tratamiento
    modelo.addColumn("Importe del tratamiento ");// importe del tratamiento
    modelo.addColumn("Estado "); //estado del tratamiento
    
    jTablaTratamientos.setModel(modelo);
}
private void cargarTabla(){
    VisitaData visitData= new VisitaData();
    
    List<Visita> visitas= visitData.listarVisitas();
    for (Visita visit:visitas){
        modelo.addRow(new Object[]{ 
            visit.getFechaVisita(),
            visit.getTratamiento().getTipoTratamiento(),
            visit.getMascota().getNombreAlias(),
            visit.getTratamiento().getDescripcion(),
            visit.getTratamiento().getImporte(),
            visit.getTratamiento().isEstadoTratamiento()
        
        });
    }
}
    private void borrarFilas() {
        int f = jTablaTratamientos.getRowCount() - 1;

        for (int i = f; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }


}
